<?php

namespace mihoshi\hashValidator;

use mihoshi\hashValidator\loaders\yamlLoader;
use mihoshi\hashValidator\exceptions\loaderException;

class yamlLoaderTest extends hashValidatorTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        if (!function_exists('yaml_parse_file')) {
            $this->markTestIncomplete();
        }
    }

    /**
     * @throws loaderException
     * @expectedException mihoshi\hashValidator\exceptions\loaderException
     */
    public function testRead_notFound()
    {
        // 実存しないファイル
        $loader = new yamlLoader();
        $loader->load('testReadJsonXX.yml');
    }

    /**
     * @throws loaderException
     * @expectedException mihoshi\hashValidator\exceptions\loaderException
     */
    public function testRead_notYamlFormat()
    {
        // yaml以外のファイル
        $loader = new yamlLoader();
        $loader->load(__FILE__);
    }

    public function testRead_success()
    {
        $loader = new yamlLoader();
        $this->assertSame(['type' => 'int', 'min' => 0],
            $loader->load(dirname(__DIR__) . '/testData/testReadYaml01.yml'));
    }

    public function testInclude()
    {
        $loader = new yamlLoader();
        $def = $loader->load(realpath(dirname(__DIR__) . '/testData/testIncludeYaml01.yml'));
        $this->assertSame([
            "type" => "hash",
            "key" => [
                "key1" => ["type" => "int", "min" => 0,],
                'key2' => ['type' => 'int'],
            ],
        ], $def);
    }

}
